[general]
import = ["~/.config/dotfiles/alacritty/themes/rose-pine.toml"]


[env]
TERM = "xterm-256color"

[font]
normal = { family = "Cascadia Mono NF", style = "Regular" }
bold = { family = "Cascadia Mono NF", style = "Bold" }
italic = { family = "Cascadia Mono NF", style = "Italic" }
size = 12

[window]
# padding.x = 14
# padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]
