###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$terminal2 = foot
# $fileManager = xdg-open $HOME
$fileManager =  kitty yazi
# $fileManager = $terminal -e yazi
# $fileManager = dolphin
# $fileManager = thunar
$menu = wofi
# $menu = ~/.config/dotfiles/scripts/wofi-cmd
$browser = google-chrome
$browser2 = brave-browser


#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = waybar
exec-once = hyprpaper
# exec-once = ~/.config/scripts/monitor-watcher
exec-once = kanshi



exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = /usr/libexec/xdg-desktop-portal-hyprland
exec-once = /usr/libexec/xdg-desktop-portal-gtk --replace &
