$font = Cascadia Code NF

general {
    hide_cursor = true
    fail_timeout = 1000
    ignore_empty_input = true
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    color = rgba(191724ee)
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(c4a7e7ee)
    check_color = rgba(31748fee)
    fail_color = rgba(eb6f92ee)

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 30

    font_family = $font
    placeholder_text = Password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 220
    halign = center
    valign = bottom
}

# TIME
# label {
#     monitor =
#     text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
#     font_size = 90
#     font_family = $font

#     position = 0, -250
#     halign = center
#     valign = top
# }

# DATE
# label {
#     monitor =
#     text = cmd[update:30000] date +"%A, %d %B %Y" # update every 30 seconds
#     font_size = 25
#     font_family = $font

#     position = 0, -400
#     halign = center
#     valign = top
# }

# Hours
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    font_size = 112
    font_family = Adwaita Sans
    shadow_passes = 0
    shadow_size = 0

    position = 0, 220
    halign = center
    valign = center
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    font_size = 112
    font_family = Adwaita Sans
    shadow_passes = 0
    shadow_size = 0

    position = 0, 80
    halign = center
    valign = center
}

# Today
label {
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%A')" </big></b>"
    font_size = 18
    font_family = JetBrainsMono NFM

    position = 0, -15
    halign = center
    valign = center
}

# Week
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
    font_size = 14
    font_family = JetBrainsMono Nerd Font 10

    position = 0, -40
    halign = center
    valign = center
}
# label {
#     monitor =
#     text = $LAYOUT[it,en]
#     font_size = 24
#     onclick = hyprctl switchxkblayout all next

#     position = 250, -20
#     halign = center
#     valign = center
# }
