[opener]
edit =[
    { run = 'hx %s', block = true, desc = "Modifica testo", for = "unix" },
]

system =[
    { run = 'xdg-open %s', desc = "Apri nel sistema", for = "linux" },
]

[open]
prepend_rules =[
    # Se il sistema riconosce il file come testo, usa "edit"
    { mime = "text/*", use = "edit" },

    # Se è un video o un audio, usa "play"
    # { mime = "video/*", use = "play" },
    # { mime = "audio/*", use = "play" },

    # Se l'estensione è .json o .md, forza l'uso di "edit"
    { url = "*.json", use = "edit" },
    { url = "*.md", use = "edit" },

    # Regola di "fallback": per qualsiasi altra cosa, usa l'app di sistema
    { url = "*", use = "system" },
]
